# Created using winget create
# Documentation: https://github.com/microsoft/winget-pkgs

PackageIdentifier: jmo.jmo-security
PackageVersion: 0.9.0
DefaultLocale: en-US
ManifestType: version
ManifestVersion: 1.6.0
