# Sponsor links shown on the repo sidebar
# GitHub Sponsors: Monthly recurring support (preferred - 0% fees)
github: jimmy058910

# Ko-Fi: One-time donations and monthly support
ko_fi: jmogaming

# Other platforms (uncomment if you use them):
# open_collective: your-collective
# patreon: your-patreon-username
# custom: ["https://your-donation-link.example.com"]
