# Sponsor links shown on the repo sidebar
# Uncomment and set your handle(s) when ready
# github: [ your-github-username ]
# ko_fi: your-kofi-username
# open_collective: your-collective
# custom: ["https://your-donation-link.example.com"]
