repos:
  # Basic sanity hooks (combined set)
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
        # Exclude multi-document YAML files (check-yaml only supports single docs)
        # - Kubernetes manifests with multiple resources
        # - Docker Compose files
        # - GitHub Actions workflow examples
        # - MkDocs config (uses !ENV tags not supported by standard YAML parser)
        exclude: ^(tests/e2e/fixtures/iac/.*\.yaml|docker-compose\.yml|docs/examples/github-actions-docker\.yml|mkdocs\.yml)$
      - id: check-json
      - id: check-toml
      - id: mixed-line-ending
      - id: detect-private-key
      # Prevent committing very large files by mistake (limit also enforced by guardrails in CI)
      - id: check-added-large-files
        args: ["--maxkb=10240"]  # 10 MB

  # Strict YAML linting (schema-agnostic)
  - repo: https://github.com/adrienverge/yamllint
    rev: v1.35.1
    hooks:
      - id: yamllint
        args: ["-c", ".yamllint.yaml", "."]

  # Validate GitHub Actions workflows
  - repo: https://github.com/rhysd/actionlint
    rev: v1.7.1
    hooks:
      - id: actionlint
        # Enable colorized output in local runs; CI may ignore colors
        args: ["-color"]

  # Markdown linting
  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.41.0
    hooks:
      - id: markdownlint

  # Python lint/format
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.6.9
    hooks:
      - id: ruff
        args: ["--fix"]
  - repo: https://github.com/psf/black
    rev: 24.8.0
    hooks:
      - id: black

  # Type checking
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.14.1
    hooks:
      - id: mypy
        additional_dependencies: [types-PyYAML]
        args: [--config-file=pyproject.toml]
        files: ^scripts/

  # Security and shell formatting
  - repo: https://github.com/PyCQA/bandit
    rev: 1.7.9
    hooks:
      - id: bandit
        name: bandit (scripts only)
        args: ["-q", "-r", "scripts", "-c", "bandit.yaml"]
        pass_filenames: false
  - repo: https://github.com/shellcheck-py/shellcheck-py
    rev: v0.10.0.1
    hooks:
      - id: shellcheck
        args: ["-S", "error", "-e", "SC2016,SC2028"]
  - repo: https://github.com/scop/pre-commit-shfmt
    rev: v3.6.0-1
    hooks:
      - id: shfmt

  # Local hook: keep requirements-dev.txt fresh when requirements-dev.in changes
  - repo: local
    hooks:
      - id: deps-compile
        name: deps-compile (generate requirements-dev.txt)
        language: system
        files: ^requirements-dev\.in$
        pass_filenames: false
        entry: make deps-compile
