extends: default

rules:
  line-length:
    max: 140
    allow-non-breakable-words: true
  truthy:
    allowed-values: ["true", "false", "yes", "no", "on", "off"]
    level: warning
  document-start: disable
  indentation:
    indent-sequences: consistent
  comments:
    min-spaces-from-content: 1
  comments-indentation: disable

ignore: |
  build/
  dist/
  .venv/
  results/
  scripts/api/node_modules/
