#!/usr/bin/env bash
# JMo Security Scan Script (generated by wizard)
set -euo pipefail

jmo scan --repos-dir C:\Projects\jmo-security-repo --results-dir results --profile-name balanced --allow-missing-tools --human-logs
