#!/usr/bin/env python3
"""
Artifact generators for the JMo Security wizard.

Extracted from wizard.py to reduce file size (959 → ~750 lines).

Functions:
- generate_makefile_target(): Creates Makefile .PHONY target
- generate_shell_script(): Creates standalone Bash script
- generate_github_actions(): Creates GitHub Actions YAML workflow
"""

from __future__ import annotations

from typing import TYPE_CHECKING, Any, Dict, List, cast

if TYPE_CHECKING:
    pass


def generate_makefile_target(config: Any, command: str) -> str:
    """
    Generate a Makefile target for security scanning.

    Args:
        config: Wizard configuration object
        command: Pre-generated jmotools command string

    Returns:
        Makefile target content with .PHONY directive
    """
    return f"""
# JMo Security Scan Target (generated by wizard)
.PHONY: security-scan
security-scan:
\t{command}
"""


def generate_shell_script(config: Any, command: str) -> str:
    """
    Generate a standalone shell script for security scanning.

    Args:
        config: Wizard configuration object
        command: Pre-generated jmotools command string

    Returns:
        Bash script content with shebang and error handling
    """
    return f"""#!/usr/bin/env bash
# JMo Security Scan Script (generated by wizard)
set -euo pipefail

{command}
"""


def generate_github_actions(config: Any, profiles: Dict[str, Any]) -> str:
    """
    Generate a GitHub Actions workflow for security scanning.

    Creates either Docker-based or native workflow depending on config.use_docker.

    Args:
        config: Wizard configuration object
        profiles: PROFILES dictionary from wizard module

    Returns:
        GitHub Actions YAML workflow content
    """
    profile_info = profiles[config.profile]
    profile_threads = cast(int, profile_info["threads"])
    profile_timeout = cast(int, profile_info["timeout"])
    threads = config.threads or profile_threads
    timeout = config.timeout or profile_timeout

    if config.use_docker:
        # Docker-based workflow
        scan_cmd_lines = [
            f"jmo scan --repo . --results results --profile {config.profile}",
            f"--threads {threads}",
            f"--timeout {timeout}",
        ]
        if config.fail_on:
            scan_cmd_lines.append(f"--fail-on {config.fail_on}")
        scan_cmd = " \\\n            ".join(scan_cmd_lines)

        return f"""name: Security Scan
on:
  push:
    branches: [main]
  pull_request:
  schedule:
    - cron: '0 0 * * 0'  # Weekly

jobs:
  security-scan:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/jimmy058910/jmo-security:latest
    steps:
      - uses: actions/checkout@v4

      - name: Run Security Scan
        run: |
          {scan_cmd}

      - name: Upload Results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: security-results
          path: results/

      - name: Upload SARIF
        if: always()
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: results/summaries/findings.sarif
"""
    else:
        # Native workflow
        scan_cmd_lines = [
            f"jmotools {config.profile} --repos-dir . --results-dir results",
            f"--threads {threads}",
            f"--timeout {timeout}",
        ]
        if config.fail_on:
            scan_cmd_lines.append(f"--fail-on {config.fail_on}")
        scan_cmd = " \\\n            ".join(scan_cmd_lines)

        profile_tools = cast(List[str], profile_info["tools"])
        tools_list = ", ".join(profile_tools)

        return f"""name: Security Scan
on:
  push:
    branches: [main]
  pull_request:
  schedule:
    - cron: '0 0 * * 0'  # Weekly

jobs:
  security-scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install JMo Security
        run: pip install jmo-security

      - name: Install Security Tools
        run: |
          # Install based on profile: {config.profile}
          # Tools: {tools_list}
          # See: https://github.com/jimmy058910/jmo-security-repo#tool-installation

      - name: Run Security Scan
        run: |
          {scan_cmd}

      - name: Upload Results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: security-results
          path: results/

      - name: Upload SARIF
        if: always()
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: results/summaries/findings.sarif
"""
