#!/usr/bin/env python3
"""Drift guard: uv.lock must stay universal (all platform markers preserved).

The migration to a tracked `uv.lock` exists to make one specific failure
impossible. Before it, `requirements-dev.txt` was generated by
`uv pip compile --universal` but *edited in place* by Dependabot's Linux-only
pip resolver. That resolver dropped platform-conditional entries -- notably:

    pywin32==312 ; sys_platform == 'win32'   # via mcp

so a fresh install on Windows omitted `pywin32` and broke `mcp`. The bug was
invisible on CI's Linux runners and only bit the maintainer, who develops on
Windows.

`uv.lock` is universal by construction -- `uv lock` has no `--python-platform`
flag, so it cannot be narrowed from the command line. The one way to narrow it
is `[tool.uv] environments` in pyproject.toml. Verified: adding
`environments = ["sys_platform == 'linux'"]` makes uv report
"Removed pywin32 v312" and reproduces the original bug exactly. These tests are
the alarm for that, and for a hand-edited lock.
"""

from __future__ import annotations

import re
from pathlib import Path

import pytest

REPO_ROOT = Path(__file__).resolve().parents[2]
UV_LOCK = REPO_ROOT / "uv.lock"


@pytest.fixture(scope="module")
def lock_text() -> str:
    if not UV_LOCK.exists():
        pytest.fail(
            "uv.lock is missing. It is the project's only lockfile and MUST be "
            "tracked in git. Regenerate with: uv lock"
        )
    return UV_LOCK.read_text(encoding="utf-8")


def test_lock_contains_windows_only_dependency(lock_text: str) -> None:
    """pywin32 (win32-only, transitive via mcp) must be present in the lock."""
    assert re.search(r'^name = "pywin32"$', lock_text, re.MULTILINE), (
        "pywin32 is absent from uv.lock. This is the exact regression the "
        "migration away from requirements-dev.txt was built to prevent: a "
        "platform-restricted resolve drops win32-only transitive deps, and "
        "`mcp` then fails to import on Windows. Check pyproject.toml for a "
        "[tool.uv] environments key, then regenerate with a plain `uv lock`."
    )


def test_lock_carries_win32_platform_markers(lock_text: str) -> None:
    """The lock must carry win32 markers, not just resolve for Linux."""
    assert "sys_platform == 'win32'" in lock_text, (
        "uv.lock has no sys_platform == 'win32' markers, which means it was "
        "resolved for a single platform instead of universally. Cross-platform "
        "dev installs (Windows/macOS) will be silently wrong."
    )


def test_lock_enumerates_wheels_for_every_ci_platform(lock_text: str) -> None:
    """The lock must carry wheels for macOS, Linux and Windows.

    uv emits a `marker = ...` only when a dependency *edge* is conditional
    (pywin32 is pulled in solely on win32). macOS and Linux need no marker
    because every package in this graph is required on both -- what differs is
    the wheel *artifact*. So platform universality for those two is proved by
    the presence of their wheel URLs, not by markers.

    This is the assertion a narrowed resolve breaks: with
    `[tool.uv] environments = ["sys_platform == 'linux'"]` the macosx and win_*
    wheels vanish, and CI's macOS and Windows shards resolve from an
    incomplete lock.
    """
    missing = [
        tag for tag in ("macosx", "manylinux", "win_amd64") if f"{tag}" not in lock_text
    ]
    assert not missing, (
        f"uv.lock has no wheels tagged {missing}, so it was resolved for a "
        "restricted set of platforms rather than universally. CI runs ubuntu, "
        "macOS and Windows shards. Regenerate with a plain `uv lock` (no "
        "--python-platform restriction)."
    )


def test_requirements_dev_files_are_gone() -> None:
    """The dual-writer files must stay deleted -- re-adding one re-arms the drift bug."""
    for stale in ("requirements-dev.in", "requirements-dev.txt"):
        assert not (REPO_ROOT / stale).exists(), (
            f"{stale} is back. It was deleted deliberately: a second "
            "dependency file with a second writer (Dependabot's pip resolver) "
            "is the root cause of the deps-compile drift class. Declare dev "
            "deps in pyproject.toml's [dependency-groups] instead."
        )
