---
name: Release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

env:
  REGISTRY_GHCR: ghcr.io
  REGISTRY_DOCKERHUB: docker.io
  IMAGE_NAME_GHCR: ${{ github.repository_owner }}/jmo-security  # GitHub: jimmy058910/jmo-security
  IMAGE_NAME_DOCKERHUB: jmogaming/jmo-security                  # Docker Hub: jmogaming/jmo-security

permissions:
  contents: read
  packages: write
  id-token: write         # For OIDC (PyPI Trusted Publishers + GitHub OIDC)
  security-events: write  # For uploading SARIF files to GitHub Security

jobs:
  # Build and publish Python package to PyPI
  pypi-publish:
    name: Build and publish to PyPI
    runs-on: ubuntu-latest
    concurrency:
      group: release-pypi-${{ github.ref }}
      cancel-in-progress: false
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: pip
          cache-dependency-path: requirements-dev.txt

      - name: Install build backend
        run: |
          python -m pip install --upgrade pip
          pip install build twine

      - name: Verify tag matches version
        run: |
          VERSION=$(python -c 'import tomllib,sys;print(tomllib.load(open("pyproject.toml","rb"))["project"]["version"])')
          TAG=${GITHUB_REF##*/}
          if [ "v$VERSION" != "$TAG" ]; then
            echo "Tag $TAG does not match project version v$VERSION" >&2
            exit 1
          fi

      - name: Build sdist/wheel
        run: python -m build

      - name: Check package metadata
        run: python -m twine check dist/*

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dist-${{ github.ref_name }}
          path: dist/*

      - name: Publish to PyPI
        if: startsWith(github.ref, 'refs/tags/v')
        uses: pypa/gh-action-pypi-publish@v1.12.4

  # Build and push multi-arch Docker images
  docker-build:
    name: Build Docker ${{ matrix.variant }}
    runs-on: ubuntu-latest
    needs: pypi-publish
    strategy:
      fail-fast: false
      matrix:
        variant: [full, slim, alpine]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY_GHCR }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Log in to Docker Hub
        if: vars.DOCKERHUB_ENABLED == 'true'
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY_DOCKERHUB }}
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ${{ env.REGISTRY_GHCR }}/${{ env.IMAGE_NAME_GHCR }}
            ${{ vars.DOCKERHUB_ENABLED == 'true' && format('{0}/{1}', env.REGISTRY_DOCKERHUB, env.IMAGE_NAME_DOCKERHUB) || '' }}
          tags: |
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            type=raw,value=latest,enable=${{ startsWith(github.ref, 'refs/tags/v') }}
          flavor: |
            suffix=-${{ matrix.variant }},onlatest=true
            latest=false

      - name: Determine Dockerfile
        id: dockerfile
        run: |
          if [ "${{ matrix.variant }}" = "full" ]; then
            echo "file=Dockerfile" >> "$GITHUB_OUTPUT"
          else
            echo "file=Dockerfile.${{ matrix.variant }}" >> "$GITHUB_OUTPUT"
          fi

      - name: Build and push
        id: build
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ${{ steps.dockerfile.outputs.file }}
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha,scope=${{ matrix.variant }}
          cache-to: type=gha,mode=max,scope=${{ matrix.variant }}
          provenance: false
          sbom: false

      - name: Test image (amd64 only)
        run: |
          # Use the first tag from metadata output (e.g., 0.4.0-full)
          TEST_TAG=$(echo "${{ steps.meta.outputs.tags }}" | head -n1 | cut -d':' -f2)

          echo "Testing image: ${{ env.REGISTRY_GHCR }}/${{ env.IMAGE_NAME_GHCR }}:${TEST_TAG}"
          docker pull --platform linux/amd64 "${{ env.REGISTRY_GHCR }}/${{ env.IMAGE_NAME_GHCR }}:${TEST_TAG}"
          # Test basic commands (jmo CLI doesn't have --version, use --help instead)
          docker run --rm --platform linux/amd64 "${{ env.REGISTRY_GHCR }}/${{ env.IMAGE_NAME_GHCR }}:${TEST_TAG}" --help
          docker run --rm --platform linux/amd64 "${{ env.REGISTRY_GHCR }}/${{ env.IMAGE_NAME_GHCR }}:${TEST_TAG}" scan --help

  # Benchmark image sizes (v0.6.1+ optimization tracking)
  docker-size-benchmark:
    name: Benchmark Docker Image Sizes
    runs-on: ubuntu-latest
    needs: docker-build
    steps:
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY_GHCR }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Determine image tag
        id: tag
        run: |
          if [ "${{ github.ref_type }}" = "tag" ]; then
            VERSION="${{ github.ref_name }}"
            VERSION="${VERSION#v}"  # Strip 'v' prefix
            echo "value=${VERSION}" >> "$GITHUB_OUTPUT"
          else
            echo "value=latest" >> "$GITHUB_OUTPUT"
          fi

      - name: Pull and measure all variants
        run: |
          {
            echo "## Docker Image Size Comparison (v0.6.1 Optimizations)"
            echo ""
            echo "| Variant | Size (Compressed) | Size (Uncompressed) | Reduction vs v0.6.0 |"
            echo "|---------|-------------------|---------------------|---------------------|"
          } > size-comparison.md

          for VARIANT in full slim alpine; do
            TAG="${{ steps.tag.outputs.value }}-${VARIANT}"
            IMAGE="${{ env.REGISTRY_GHCR }}/${{ env.IMAGE_NAME_GHCR }}:${TAG}"

            echo "Pulling $IMAGE..."
            docker pull --platform linux/amd64 "$IMAGE"

            # Get compressed size (what users download)
            COMPRESSED=$(docker inspect "$IMAGE" | jq -r '.[0].Size' | numfmt --to=iec-i --suffix=B)

            # Get uncompressed size (disk usage after pull)
            UNCOMPRESSED=$(docker inspect "$IMAGE" | jq -r '.[0].VirtualSize' | numfmt --to=iec-i --suffix=B)

            echo "| ${VARIANT} | ${COMPRESSED} | ${UNCOMPRESSED} | TBD (manual comparison) |" >> size-comparison.md
          done

          echo "" >> size-comparison.md
          echo "**Optimization Goals (ROADMAP #1):**" >> size-comparison.md
          echo "- Full: 1.5GB → 900MB (40% reduction)" >> size-comparison.md
          echo "- Slim: 700MB → 400MB (43% reduction)" >> size-comparison.md
          echo "- Alpine: 500MB → 300MB (40% reduction)" >> size-comparison.md
          echo "" >> size-comparison.md
          echo "**Optimizations Applied:**" >> size-comparison.md
          echo "- Multi-stage builds (separate builder and runtime stages)" >> size-comparison.md
          echo "- Layer caching cleanup (apt cache, pip cache, Python bytecode)" >> size-comparison.md
          echo "- Trivy DB pre-download (eliminates 30-60s scan delay)" >> size-comparison.md

          cat size-comparison.md

      - name: Upload size comparison
        uses: actions/upload-artifact@v4
        with:
          name: docker-size-comparison-${{ steps.tag.outputs.value }}
          path: size-comparison.md

  # Scan Docker images for vulnerabilities
  docker-scan:
    name: Scan Docker ${{ matrix.variant }}
    runs-on: ubuntu-latest
    needs: docker-build
    strategy:
      matrix:
        variant: [full, slim, alpine]
    steps:
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY_GHCR }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Determine image tag
        id: tag
        run: |
          # For tags like v0.4.0, the image is tagged as 0.4.0-variant (without 'v')
          if [ "${{ github.ref_type }}" = "tag" ]; then
            VERSION="${{ github.ref_name }}"
            VERSION="${VERSION#v}"  # Strip 'v' prefix
            echo "value=${VERSION}-${{ matrix.variant }}" >> "$GITHUB_OUTPUT"
          else
            echo "value=latest-${{ matrix.variant }}" >> "$GITHUB_OUTPUT"
          fi

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ${{ env.REGISTRY_GHCR }}/${{ env.IMAGE_NAME_GHCR }}:${{ steps.tag.outputs.value }}
          format: 'sarif'
          output: 'trivy-results-${{ matrix.variant }}.sarif'
          severity: 'CRITICAL,HIGH'

      - name: Upload Trivy results to GitHub Security
        uses: github/codeql-action/upload-sarif@v4
        with:
          sarif_file: 'trivy-results-${{ matrix.variant }}.sarif'
          category: 'docker-${{ matrix.variant }}'

  # Update Docker Hub README
  docker-hub-readme:
    name: Update Docker Hub README
    runs-on: ubuntu-latest
    needs: docker-build
    # Only run on version tags (v*), skip on workflow_dispatch
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v')
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Update Docker Hub description
        # Requires secrets: DOCKERHUB_USERNAME and DOCKERHUB_TOKEN (PAT with read/write/delete scope)
        # Create PAT at: https://hub.docker.com/settings/security
        # Add secrets at: https://github.com/${{ github.repository }}/settings/secrets/actions
        if: vars.DOCKERHUB_ENABLED == 'true'
        uses: peter-evans/dockerhub-description@v5
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          repository: ${{ env.IMAGE_NAME_DOCKERHUB }}
          short-description: "JMo Security Suite - Terminal-first security audit toolkit with 14 tools, multi-target scanning"
          readme-filepath: ./DOCKER_HUB_README.md

      - name: Docker Hub update skipped
        if: vars.DOCKERHUB_ENABLED != 'true'
        run: |
          echo "Docker Hub README update skipped."
          echo "To enable:"
          echo "1. Create Docker Hub PAT: https://hub.docker.com/settings/security"
          echo "2. Add secrets DOCKERHUB_USERNAME and DOCKERHUB_TOKEN"
          echo "3. Set repository variable DOCKERHUB_ENABLED=true"
