name: Release (PyPI)

on:
  push:
    tags:
      - 'v*'

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install build backend
        run: |
          python -m pip install --upgrade pip
          pip install build twine
      - name: Build sdist/wheel
        run: |
          python -m build
      - name: Publish to PyPI
        if: startsWith(github.ref, 'refs/tags/v')
        uses: pypa/gh-action-pypi-publish@v1.12.2
        with:
          packages_dir: dist
