name: Tests

on:
  push:
  pull_request:

concurrency:
  group: tests-${{ github.workflow }}-${{ github.ref || github.run_id }}
  cancel-in-progress: true

jobs:
  tests:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 20
    permissions:
      contents: read
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
        python-version: ["3.10", "3.11", "3.12"]
    steps:
      - uses: actions/checkout@v4
      - name: Pre-commit (YAML & misc checks)
        uses: pre-commit/action@v3.0.1
        with:
          extra_args: --all-files
      - name: Validate GitHub workflows (actionlint)
        uses: rhysd/actionlint@v1.7.1
      - name: "Guardrails: forbid tracked venv/artifacts"
        run: |
          bash scripts/dev/guardrails_check.sh
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          # Speed up dependency installs by caching pip based on requirements file hash
          cache: 'pip'
          cache-dependency-path: 'requirements-dev.txt'
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-dev.txt
          # Install the project in editable mode so 'scripts' package is importable
          pip install -e .
      - name: Lint
        run: make lint || true
      - name: Run tests with coverage
        run: |
          python -m pytest -q --maxfail=1 --disable-warnings --cov=. --cov-report=term-missing --cov-report=xml --cov-fail-under=85
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        with:
          files: ./coverage.xml
          fail_ci_if_error: false
          verbose: true
