name: Tests

on:
  push:
  pull_request:

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: "Guardrails: forbid tracked venv/artifacts"
        run: |
          bash scripts/dev/guardrails_check.sh
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          # Speed up dependency installs by caching pip based on requirements file hash
          cache: 'pip'
          cache-dependency-path: 'requirements-dev.txt'
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-dev.txt
          # Install the project in editable mode so 'scripts' package is importable
          pip install -e .
      - name: Run tests with coverage
        run: |
          python -m pytest -q --maxfail=1 --disable-warnings --cov=. --cov-report=term-missing --cov-report=xml --cov-fail-under=85
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        with:
          files: ./coverage.xml
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: false
          verbose: true
